config/routes.rb
Rails.application.routes.draw do
  get 'games/home'

  get 'games/about'

  get 'games/catalogo'

  root 'games#home'

  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_attached_file :foto, styles:
    { medium: "300x300>", thumb: "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  def home
  end

  def about
  end

  def catalogo
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:nome, :descricao, :date, :desenvolvedora, :imagem, :video, :genero, :foto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(game, html: {multipart: true}) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  


  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_area :descricao %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :desenvolvedora %>
    <%= f.text_field :desenvolvedora %>
  </div>

  <div class="field">
    <%= f.label :imagem %>
    <%= f.text_field :imagem %>
  </div>

  <div class="field">
    <%= f.label :video %>
    <%= f.text_field :video %>
  </div>

  <div class="field">
    <%= f.label :genero %>
    <%= f.text_field :genero %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

  
  </head>

  <body>

    

       
      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">EP3.</h2>
          <p class="lead">       Este projeto é um trabalho da máteria de Orientaão a Objetos do curso de Engenharia de software da Universidade de Brasília.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="https://canaldoensino.com.br/blog/wp-content/uploads/2015/02/unb_img.jpg" style=" height:200px; width:400px;">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Lucas Macêdo.</h2>
          <p class="lead">Aluno de engenharia de software do terceiro semestre da Universidade de Brasília</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="hfeaturette-image img-responsive center-block" src = "https://scontent.fbsb3-1.fna.fbcdn.net/v/t1.0-9/10981811_889354444443527_2912187393822724592_n.jpg?oh=9065bd76c6047b61afa1f31d9a889138&oe=58ECB36A" style=" height:300px; width:300px;">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Caio Oliveira.</h2>
          <p class="lead">Aluno de engenharia de software do terceiro semestre da Universidade de Brasília </p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="https://scontent.fbsb3-1.fna.fbcdn.net/v/t1.0-0/p526x296/15181418_1280719098636308_8901796031168209671_n.jpg?oh=aa75ed6b01737d590e4d9d7437301cc9&oe=58F6BA47" style="height:300px; width:300px;">
        </div>
      </div>

      <hr class="featurette-divider">

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/games/catalogo.html.erb
  <p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
     
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <div class="col-lg-4">
          <img class="img-square" src="<%= game.imagem%> " alt="battlefield" width="250" height="250">
          <h2><%= game.nome %></h2>
          
          <p><button type="button" class="btn btn-default"> <%= link_to 'Mostrar', game %></td></p>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br> 

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/home.html.erb
  
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>



    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="https://content.pulse.ea.com/content/battlefield-portal/pt_BR/news/battlefield-1/melee-combat-of-Battlefield-1/_jcr_content/featuredImage/renditions/rendition1.img.jpg" style=" height:500px; width: 1500px;" alt="First slide" >
          <div class="container">
            <div class="carousel-caption">
              <h1>Battlefield 1.</h1>
              <p>Clique e veja o detalhes do jogo.</p>
              <p><a class="btn btn-lg btn-primary" href="/games/20" role="button">Veja detalhes</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" style=" height:500px; width: 1500px;" src="https://images5.alphacoders.com/394/thumb-1920-394511.jpg"  "alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>The last of us.</h1>
              <p>Clique e veja o detalhes do jogo.</p>
              <p><a class="btn btn-lg btn-primary" href="/games/19" role="button">Veja detalhes</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" style=" height:500px; width: 1500px;" src="https://1.bp.blogspot.com/-gHXl4ZR14XM/V3ZdlNc8y6I/AAAAAAAAFMU/b6jUoCybXfgQHS-dFrh1oSpg_ytLi4XqQCLcB/w1200-h630-p-nu/street-fighter-5-02.jpg"  alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Street Fight V.</h1>
              <p>Clique e veja o detalhes do jogo</p>
              <p><a class="btn btn-lg btn-primary" href="/games/23" role="button">Veja detalhes</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing" style = "margin-top: 65px" >

      <!-- Three columns of text below the carousel -->
      
      <p>
        <font size="40">
          Jogos em Destaque
      
         </font>
      </p>

      <div class="row">
        <div class="col-lg-4">
          <img class="img-square" src="http://sm.ign.com/t/ign_br/screenshot/default/tgeedeps42dpftfront-us_mz7r.640.png" alt="battlefield" width="250" height="250">
          <h2>Battlefiled 1</h2>
          
          <p><a class="btn btn-default" href="/games/20" role="button">Veja detalhes &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-square" src="http://digitaltiger.vteximg.com.br/arquivos/ids/161543/star-wars-battlefront-box-art-ps4.jpg" alt="star wars" width="250" height="250">
          <h2>Star Wars Battlefront</h2>
          
          <p><a class="btn btn-default" href="/games/21" role="button">Veja detalhes &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-square" src="http://www.sharkgames.com.br/site/wp-content/uploads/2016/08/capa-fifa-17-ps4-jony-games.jpg " alt="Fifa" width="250" height="250">
          <h2>FIFA 17</h2>
          
          <p><a class="btn btn-default" href="/games/24" role="button">Veja detalhes &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->




    

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        
        <td><h3><%= game.nome %></h3></td>
        <p>
          
        <td>
        
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="button" class="btn btn-default" ><%= link_to 'Edit', edit_game_path(game) %></button>
        </td>
        
          <td>
          &nbsp;&nbsp;<button type="button" class="btn btn-default" ><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></button>
          </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-default" >
<%= link_to 'New Game', new_game_path %>
</button>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @game.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @game.descricao %>
</p>

<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<p>
  <strong>Desenvolvedora:</strong>
  <%= @game.desenvolvedora %>
</p>

<p>
  <strong>Imagem:</strong>
     <img class="img-square" src="<%= @game.imagem%>" alt="Fifa" width="350" height="350">
</p>

<p>
  <strong>Video:</strong>
  <iframe width="500" height="340" src="<%= @game.video %>" frameborder="0" allowfullscreen></iframe>
</p>

<p>
  <strong>Genero:</strong>
  <%= @game.genero %>
</p>


<p><button type="button" class="btn btn-default"> 
<%= link_to 'Back', games_catalogo_path %></td></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LCW</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body background= "http://4.bp.blogspot.com/-gGT-68t0nQQ/Va-HuRpWMUI/AAAAAAAAILc/QtyHS9O1wLo/s1600/fundo-cinza-fundos%2B%25287%2529.jpg">

  <!-- NAVBAR



================================================== -->



<nav class="navbar navbar-inverse">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"<%= link_to "EP3" , games_home_path %> </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Inicio" , games_home_path %></li>
        <li><%= link_to "Sobre" , games_about_path %></li>
        <li><%= link_to "Cadastro" , games_path %></li>
        <li><%= link_to "Catálogo" , games_catalogo_path %></li>
      </ul>






    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



    <%= yield %>

 
  </body>
</html>